baseURL = 'http://example.org/'
languageCode = 'ja-JP'
title = 'nemu626'
theme = 'm10c'

[params]
	author =  'nemu626'
	description = '東京都でよわよわフロントエンドエンジニアしてる。Software Engineer @Tokyo, Japan.'
	avatar = 'https://pbs.twimg.com/profile_images/2978662646/83cef7905f6a182dc40589b394372ad9_400x400.png'


[[params.social]]
	icon='github'
	name = 'My Github'
	url = 'https://github.com/nemu626'

[[params.social]]
	icon='twitter'
	name='My Twitter'
	url = 'https://twitter.com/NarugaL_ove'
